### ISSUE TITLE
how to make a standalone mac app via pyinstaller？

### ISSUE THREAD

**Issue by blacklein** [Sanster/lama-cleaner#134]
use one click installer lama-cleaner is working well on m1max mac. i try to make a mac app by using pyinstaller, but print errors. is it possible to give a ready to use .spec file in the repo? thanks!

**Comment by Sanster** [comment]
I am also learning how to make a standalone app by reading the code of [Diffusion Bee](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui) and haven't figured it out 😓 . 

BTW, How did you use the one-click installer on your mac? I tried downloading the installer and  it keeping popup a warning dialog "xxx cannot be opened because it is from an unidentified developer xxx"

**Comment by blacklein** [comment]
> I am also learning how to make a standalone app by reading the code of [Diffusion Bee](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui) and haven't figured it out 😓 . 
> 
> BTW, How did you use the one-click installer on your mac? I tried downloading the installer and  it keeping popup a warning dialog "xxx cannot be opened because it is from an unidentified developer xxx"

chmod u+x (drag config and start shell script and tasks.py here)

**Comment by blacklein** [comment]
wish to build a m1 mac app so it can be started more easily, don't how to solve it, need help please
