### ISSUE TITLE
python3.11 无法安装

### ISSUE THREAD

**Issue by FynnFbc** [Sanster/lama-cleaner#137]

**Comment by Lfw08** [comment]
我试了3.11 和3.10 都没有成功，原因应该是它依赖[torch](https://pypi.org/project/torch/) ，但是torch不支持3.10和3.11（只支持从3.7到3.9，不支持python2）。所以要么用低一点的python版本，要么等等看torch能不能支持更高版本。
[→Pytorch.org 上关于python的要求和教程](https://pytorch.org/get-started/locally/#windows-python)

**Comment by FynnFbc** [comment]
好的，明白了

**Comment by Sanster** [comment]
Thanks for pointing this out, I have updated the python version badge in the readme

<img width="825" alt="image" src="https://user-images.githubusercontent.com/3998421/206910727-5df08974-13e5-4231-a810-b153b69854ff.png">

**Comment by mayjack0312** [comment]
是的，我`python 3.11.1`安装它就显示失败
log如下
'''
ERROR: Cannot install lama-cleaner==0.10.0, lama-cleaner==0.11.0, lama-cleaner==0.12.0, lama-cleaner==0.13.0, lama-cleaner==0.14.0, lama-cleaner==0.15.0, lama-cleaner==0.16.0, lama-cleaner==0.17.0, lama-cleaner==0.18.0, lama-cleaner==0.19.0, lama-cleaner==0.20.0, lama-cleaner==0.20.1, lama-cleaner==0.21.0, lama-cleaner==0.22.0, lama-cleaner==0.23.0, lama-cleaner==0.24.0, lama-cleaner==0.24.1, lama-cleaner==0.24.2, lama-cleaner==0.24.3, lama-cleaner==0.24.4, lama-cleaner==0.24.5, lama-cleaner==0.25.0, lama-cleaner==0.26.0, lama-cleaner==0.26.1, lama-cleaner==0.26.2, lama-cleaner==0.27.1, lama-cleaner==0.27.2, lama-cleaner==0.28.0, lama-cleaner==0.29.0, lama-cleaner==0.29.1, lama-cleaner==0.30.0, lama-cleaner==0.9.0, lama-cleaner==0.9.1, lama-cleaner==0.9.2 and lama-cleaner==0.9.3 because these package versions have conflicting dependencies.
The conflict is caused by:
    lama-cleaner 0.30.0 depends on torch>=1.9.0
    lama-cleaner 0.29.1 depends on torch>=1.9.0
    lama-cleaner 0.29.0 depends on torch>=1.9.0
    lama-cleaner 0.28.0 depends on torch>=1.9.0
    lama-cleaner 0.27.2 depends on torch>=1.9.0
    lama-cleaner 0.27.1 depends on torch>=1.9.0
    lama-cleaner 0.26.2 depends on torch>=1.9.0
    lama-cleaner 0.26.1 depends on torch>=1.9.0
    lama-cleaner 0.26.0 depends on torch>=1.9.0
    lama-cleaner 0.25.0 depends on torch>=1.9.0
    lama-cleaner 0.24.5 depends on torch>=1.9.0
    lama-cleaner 0.24.4 depends on torch>=1.9.0
    lama-cleaner 0.24.3 depends on torch>=1.9.0
    lama-cleaner 0.24.2 depends on torch>=1.9.0
    lama-cleaner 0.24.1 depends on torch>=1.9.0
    lama-cleaner 0.24.0 depends on torch>=1.9.0
    lama-cleaner 0.23.0 depends on torch>=1.9.0
    lama-cleaner 0.22.0 depends on torch>=1.9.0
    lama-cleaner 0.21.0 depends on torch>=1.9.0
    lama-cleaner 0.20.1 depends on torch>=1.8.2
    lama-cleaner 0.20.0 depends on torch>=1.8.2
    lama-cleaner 0.19.0 depends on torch>=1.8.2
    lama-cleaner 0.18.0 depends on torch>=1.8.2
    lama-cleaner 0.17.0 depends on torch>=1.8.2
    lama-cleaner 0.16.0 depends on torch>=1.8.2
    lama-cleaner 0.15.0 depends on torch>=1.8.2
    lama-cleaner 0.14.0 depends on torch>=1.8.2
    lama-cleaner 0.13.0 depends on torch>=1.8.2
    lama-cleaner 0.12.0 depends on torch>=1.8.2
    lama-cleaner 0.11.0 depends on torch>=1.8.2
    lama-cleaner 0.10.0 depends on torch>=1.8.2
    lama-cleaner 0.9.3 depends on torch>=1.8.2
    lama-cleaner 0.9.2 depends on torch>=1.8.2
    lama-cleaner 0.9.1 depends on torch>=1.8.2
    lama-cleaner 0.9.0 depends on torch>=1.8.2
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
'''

**Comment by Lfw08** [comment]
> Thanks for pointing this out, I have updated the python version badge in the readme
> 
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/3998421/206910727-5df08974-13e5-4231-a810-b153b69854ff.png">

![IMG_20230612_215753](https://github.com/Sanster/lama-cleaner/assets/104214082/dd991369-68d7-4053-8438-972f362c84c4)
take a look at this: now pytorch on windows supports 3.11 and 3.10, so I think now there shouldn't be any problems when installing with pip using 3.11 and the badge can be changed to ≥3.8.

**Comment by Lfw08** [comment]
> > Thanks for pointing this out, I have updated the python version badge in the readme
> > <img alt="image" width="825" src="https://user-images.githubusercontent.com/3998421/206910727-5df08974-13e5-4231-a810-b153b69854ff.png">
> 
> ![IMG_20230612_215753](https://user-images.githubusercontent.com/104214082/245166717-dd991369-68d7-4053-8438-972f362c84c4.png) take a look at this: now pytorch on windows supports 3.11 and 3.10, so I think now there shouldn't be any problems when installing with pip using 3.11 and the badge can be changed to ≥3.8.

wait where did the image go?
![IMG_20230612_215753](https://github.com/Sanster/lama-cleaner/assets/104214082/38ed5e97-489c-4262-ae7d-8bf28914354e)
