### ISSUE TITLE
0.9.2 install and launch issues

### ISSUE THREAD

**Issue by flagshipbowtie** [Sanster/lama-cleaner#41]
conda create -n LAMA
conda activate LAMA
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch
pip install lama-cleaner
I get this 
![Pyton](https://user-images.githubusercontent.com/103138306/163865290-cfa9aa34-1d66-4a5b-8235-55fd8aace95d.PNG)
When I go try to launch I surely get an issue 

![Pyton 2](https://user-images.githubusercontent.com/103138306/163865369-2baefea2-d447-4344-82ab-bd7092eddf5d.PNG)

Running 0.8.0 and all releases before with no issues

**Comment by flagshipbowtie** [comment]
> 2. The torch version you installed does not support GPU
Hmm? It does. I've used all the previous versions of your code running on GPU. This line literally installs GPU support > conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch

**Comment by Sanster** [comment]
> That's exactly what I did.

No. You install torchvision/torchaudio first `conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch`, that's why the incompatible error happen.

> GPU issue

I don't have a windows test environment, it seems to be a bug with the torch on Windows(pytorch 1.11.0 should work with lama model) [GPU is not available for Pytorch](https://stackoverflow.com/questions/69694093/gpu-is-not-available-for-pytorch), if torch 1.8.0 works for you can just run `pip install torch==1.8.0` to switch to 1.8.0

> zoom issue

fixed in 0.9.3

**Comment by flagshipbowtie** [comment]
> No. You install torchvision/torchaudio first `conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch`, that's why the incompatible error happen.

The order matters? Never mattered before.

> I don't have a windows test environment, it seems to be a bug with the torch on Windows(pytorch 1.11.0 should work with lama model) [GPU is not available for Pytorch](https://stackoverflow.com/questions/69694093/gpu-is-not-available-for-pytorch), if torch 1.8.0 works for you can just run `pip install torch==1.8.0` to switch to 1.8.0

No I never installed 1.11. I can't. Running Windows7. I installed 1.8.0. Like I said GPU works on 0.8.0 and below of your code

I get it you changed the instruction to simplify the install and use but that's the problem occurs for some reason 

> > zoom issue
> fixed in 0.9.3

Great!

**Comment by flagshipbowtie** [comment]
Just publish with the old install instructions as option 2. They worked fine. This PyPI install doesn't work and I can't run it on GPU
