### ISSUE TITLE
Reasons for failing watermark removal 

### ISSUE THREAD

**Issue by cgiturtle** [Sanster/lama-cleaner#603]
thankful for any pointers 

```
iopaint run --model=lama --device=cpu \
--image=/inputdir/ \
--mask=/mask-artlist.png \
--output=/outputdir/
```

![out422](https://github.com/user-attachments/assets/1ba3267e-e0f8-404e-9cda-e0911a003350)
![mask-artlist](https://github.com/user-attachments/assets/568ec9f7-350f-4cbd-9272-69b92eb3eaa2)

**Comment by Sanster** [comment]
- The white area on the mask will be considered as the area that needs to be inpainted.
- Your mask is a PNG image with a transparent channel. The first three channels, RGB, are pure black and need to be converted, keeping the alpha channel as the mask. Below is the conversion code and the converted mask.

```python
import cv2
img = cv2.imread("mask.png", cv2.IMREAD_UNCHANGED)
alpha = img[:, :, 3]
cv2.imwrite("real_mask.jpg", alpha)
```

![real_mask](https://github.com/user-attachments/assets/0945a0bd-7c54-4a82-9275-3b0d85109847)

The result

![input](https://github.com/user-attachments/assets/5d88b488-f4a3-40ad-b56f-7e807d78030b)

You can see that the inpaint results around the original mask are not very good; this is because the model expects the mask to be slightly larger than the original target, we can perform dilation on the mask.

```python
import cv2

img = cv2.imread("mask.png", cv2.IMREAD_UNCHANGED)
alpha = img[:, :, 3]
cv2.imwrite("real_mask.jpg", alpha)

kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
alpha_dilated = cv2.dilate(alpha, kernel, iterations=1)
alpha = alpha_dilated
cv2.imwrite("mask_dilated.jpg", alpha)
```

The following is the expanded mask and the inpaint result.

![mask_dilated](https://github.com/user-attachments/assets/0ad1fc8d-8a2d-4e62-9277-c9cced07c050)

![input](https://github.com/user-attachments/assets/057e0776-9525-4545-ab4e-32ee4aec172a)


If I was able to help you resolve your problem, please consider [buying me a coffee](https://ko-fi.com/Z8Z1CZJGY) to show your appreciation.
