### ISSUE TITLE
SD 1.5 model error

### ISSUE THREAD

**Issue by mykeehu** [Sanster/lama-cleaner#95]
There is a problem because the SD 1.5 model cannot be selected, only 1.4, but it runs into the error that it is not supported. I am using version 0.24.
Here is my command: lama-cleaner --model=lama --device=cuda --port=9876 --gui --sd-disable-nsfw --sd-run-local

![image](https://user-images.githubusercontent.com/6390413/197125795-24ab8d7c-40a3-4729-ab0e-af152d22a7f8.png)
and after upgrade:
![image](https://user-images.githubusercontent.com/6390413/197125953-b4b5a631-d516-42d8-a7ed-c4dcf24a7da0.png)
![image](https://user-images.githubusercontent.com/6390413/197125605-6dd00921-2e49-4135-8511-38bead911b37.png)
![image](https://user-images.githubusercontent.com/6390413/197125648-d84a4d3c-b159-4c62-a1bb-af7fd19e8bd7.png)

**Comment by Sanster** [comment]
You need to [accept the terms](https://huggingface.co/runwayml/stable-diffusion-inpainting) to access runway my/stable-diffusion-inpainting model, and get an access token from here [huggingface access token](https://huggingface.co/docs/hub/security-tokens). Start lama-cleaner with huggingface access token:

```bash
lama-cleaner --model=sd1.5 --hf_access_token=hf_xxx
```

The reason why the front-end page cannot select `sd1.5` may be due to caching, please clear the browser cache and try again

**Comment by mykeehu** [comment]
After entering the command and downloading the 1.5 SD model, I started the GUI and pressed CTRL+F5, and the interface was updated, the 1.5 model appeared in the list.
Thank you very much for your quick help!
